### PR TITLE
change version

### PR DESCRIPTION
**Pull request by NiyooshaJafari**

### CODE REVIEW

**Comment by martin-loetzsch** [comment]
@NiyooshaJafari is that running in production at your company?

**Comment by martin-loetzsch** [comment]
@flaviobrito can you check this?

**Comment by NiyooshaJafari** [comment]
@martin-loetzsch yes it is running in production.

**Comment by Vaaceph** [comment]
@martin-loetzsch, I also checked it for facebook_business version 6.0.2 and its working fine.

**Comment by henryhinze** [comment]
I checked it too. It's running fine for two of my clients.

**Pull request merged**
